export const CHECK_USER_ADMIN = "CHECK_USER_ADMIN";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";

export const STUDENT_ENROLLMENT_REQUEST = "ENROLLMENT_REQUEST";
export const STUDENT_ENROLLMENT_SUCCESS = "STUDENT_ENROLLMENT_SUCCESS";
export const STUDENT_ENROLLMENT_FAILED = "STUDENT_ENROLLMENT_FAILED";
export const STUDENT_ENROLLED_CHECK = "STUDENT_ENROLLED_CHECK";
export const CLEAR_ENROLLMENT_DATA = "CLEAR_ENROLLMENT_DATA";
